import { useMemo, useState } from 'react'
import { Plus, Receipt, Trash2, Wallet } from 'lucide-react'
import Modal from '../components/Modal.jsx'
import StatCard from '../components/StatCard.jsx'
import { useLocalStore } from '../lib/useLocalStore.js'
import { STORAGE_KEYS, EXPENSE_CATEGORIES, fmtUSD, isCurrentMonth, todayISO } from '../lib/lifeStore.js'

export default function Expenses() {
  const [items, api] = useLocalStore(STORAGE_KEYS.expenses, [])
  const [open, setOpen] = useState(false)
  const month = useMemo(() => items.filter((x) => isCurrentMonth(x.date)), [items])
  const business = month.filter((x) => ['business', 'salon', 'supply'].includes(x.category)).reduce((s, x) => s + Number(x.amount || 0), 0)
  const total = month.reduce((s, x) => s + Number(x.amount || 0), 0)
  return <div className="container-app py-6 sm:py-8"><div className="flex items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-ink-900 flex items-center gap-2"><Receipt className="w-7 h-7 text-brand-600" /> Expenses</h1><p className="text-ink-500 mt-1">Nhập tay cho nhanh, không scan hình để tiết kiệm chi phí AI.</p></div><button className="btn-primary" onClick={() => setOpen(true)}><Plus className="w-4 h-4" /> Add</button></div><section className="mt-5 grid sm:grid-cols-3 gap-3"><StatCard label="This month" value={fmtUSD(total)} icon={Wallet} tone="brand" /><StatCard label="Business" value={fmtUSD(business)} /><StatCard label="Personal/Other" value={fmtUSD(total - business)} /></section><div className="mt-5 card p-5"><h2 className="font-bold text-ink-900">Expense list</h2>{items.length === 0 ? <p className="py-10 text-center text-sm text-ink-400">Chưa có chi tiêu.</p> : <ul className="mt-3 divide-y divide-ink-100">{items.map((e) => <li key={e.id} className="py-3 flex items-center justify-between gap-3"><div><p className="font-semibold text-ink-900">{e.title}</p><p className="text-xs text-ink-500">{e.date} • {e.category}</p></div><div className="flex items-center gap-3"><span className="font-bold text-ink-900">{fmtUSD(e.amount)}</span><button onClick={() => api.remove(e.id)} className="text-ink-300 hover:text-rose-600"><Trash2 className="w-4 h-4" /></button></div></li>)}</ul>}</div><ExpenseModal open={open} onClose={() => setOpen(false)} onSave={(item) => { api.add(item); setOpen(false) }} /></div>
}
function ExpenseModal({ open, onClose, onSave }) { const [form, setForm] = useState({ title: '', amount: '', category: 'personal', date: todayISO(), note: '' }); const save = () => { if (!form.title || !form.amount) return; onSave({ ...form, amount: Number(form.amount) }); setForm({ title: '', amount: '', category: 'personal', date: todayISO(), note: '' }) }; return <Modal open={open} onClose={onClose} title="Add expense" footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" onClick={save}>Save</button></>}><Field label="Title" value={form.title} onChange={(v) => setForm({ ...form, title: v })} /><Field label="Amount" type="number" value={form.amount} onChange={(v) => setForm({ ...form, amount: v })} /><label className="label">Category</label><select className="input mb-3" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{EXPENSE_CATEGORIES.map((c) => <option key={c.key} value={c.key}>{c.label} / {c.vi}</option>)}</select><Field label="Date" type="date" value={form.date} onChange={(v) => setForm({ ...form, date: v })} /><Field label="Note" value={form.note} onChange={(v) => setForm({ ...form, note: v })} /></Modal> }
function Field({ label, value, onChange, type = 'text' }) { return <label className="block mb-3"><span className="label">{label}</span><input className="input" type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label> }
