import { Link } from 'react-router-dom'
import { ArrowRight, Bell, CalendarDays, FileText, Receipt, Shield, Sparkles, WalletCards } from 'lucide-react'
import Logo from '../components/Logo.jsx'
import LanguageToggle from '../components/LanguageToggle.jsx'
import Footer from '../components/Footer.jsx'

export default function Landing() {
  return <div className="min-h-screen bg-white"><header className="absolute top-0 inset-x-0 z-20"><div className="container-app flex items-center justify-between h-16"><Logo /><div className="flex items-center gap-3"><Link to="/pricing" className="hidden sm:block text-sm font-semibold text-ink-700 hover:text-ink-900">Pricing</Link><LanguageToggle /><Link to="/login" className="hidden sm:inline-flex btn-ghost text-sm">Log in</Link><Link to="/signup" className="btn-primary text-sm !px-4 !py-2">Start free</Link></div></div></header><section className="hero-gradient pt-32 pb-20 sm:pt-40 sm:pb-28"><div className="container-app"><div className="max-w-3xl mx-auto text-center animate-fade-up"><span className="badge bg-brand-50 text-brand-700 mb-5"><Sparkles className="w-3.5 h-3.5" /> Daily life app for Vietnamese in the U.S.</span><h1 className="font-display text-4xl sm:text-5xl md:text-6xl font-extrabold text-ink-900 leading-[1.05]">Open it every day. Remember less. Track better.</h1><p className="mt-5 text-lg sm:text-xl text-ink-600 max-w-2xl mx-auto">Reminder, monthly bills, personal expenses, business expenses, and year-end summaries — simple enough to use every day.</p><div className="mt-8 flex flex-col sm:flex-row justify-center gap-3"><Link to="/signup" className="btn-primary">Start free <ArrowRight className="w-4 h-4" /></Link><Link to="/pricing" className="btn-secondary">View plans</Link></div><p className="mt-3 text-xs text-ink-400">No unlimited AI chat. No receipt scan. No tax advice. Just practical daily tracking.</p></div><HeroMock /></div></section><section className="py-20"><div className="container-app"><div className="max-w-2xl mx-auto text-center"><h2 className="text-3xl font-extrabold text-ink-900">Core features</h2><p className="mt-3 text-ink-600">Personal and Business share one Today page. Category handles the separation.</p></div><div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-4 gap-5"><Feature icon={CalendarDays} title="Today page" text="The home screen after login: reminders, bills, expenses, smart insight." /><Feature icon={Bell} title="Reminders" text="Natural quick add, repeat tasks, family reminders, bill reminders." /><Feature icon={Receipt} title="Expenses" text="Manual entry for personal and business expenses. Fast and cheap to run." /><Feature icon={FileText} title="Summary" text="Monthly/yearly totals you can hand to your tax preparer. No tax advice." /></div></div></section><section className="py-16 bg-ink-50 border-y border-ink-100"><div className="container-app grid sm:grid-cols-3 gap-6"><Value icon={WalletCards} title="Free works" text="Basic reminder, expense, Today page and light limits." /><Value icon={Sparkles} title="AI is light" text="Natural reminder parsing, daily insight, limited smart actions." /><Value icon={Shield} title="Cost controlled" text="Daily summary is cached; no AI call every time the app opens." /></div></section><Footer /></div>
}
function HeroMock() { return <div className="mt-14 max-w-4xl mx-auto card p-4 sm:p-6 text-left"><div className="grid md:grid-cols-3 gap-3"><div className="rounded-2xl bg-brand-50 p-4"><p className="text-xs font-bold text-brand-700">TODAY</p><p className="mt-2 text-2xl font-extrabold text-ink-900">3 reminders</p><p className="text-sm text-ink-500">Pay electric bill at 9 PM</p></div><div className="rounded-2xl bg-white border border-ink-100 p-4"><p className="text-xs font-bold text-ink-500">THIS MONTH</p><p className="mt-2 text-2xl font-extrabold text-ink-900">$1,240</p><p className="text-sm text-ink-500">Business + personal expenses</p></div><div className="rounded-2xl bg-gold-500/10 p-4"><p className="text-xs font-bold text-gold-700">SMART INSIGHT</p><p className="mt-2 text-sm text-ink-700">You have 2 bills due soon. Add today’s expenses before you forget.</p></div></div></div> }
function Feature({ icon: Icon, title, text }) { return <div className="card p-5"><div className="w-10 h-10 rounded-xl bg-brand-50 text-brand-700 flex items-center justify-center"><Icon className="w-5 h-5" /></div><h3 className="mt-4 font-bold text-ink-900">{title}</h3><p className="mt-2 text-sm text-ink-500">{text}</p></div> }
function Value({ icon: Icon, title, text }) { return <div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-white border border-ink-100 text-brand-700 flex items-center justify-center"><Icon className="w-5 h-5" /></div><div><h3 className="font-bold text-ink-900">{title}</h3><p className="text-sm text-ink-500">{text}</p></div></div> }
