import { Link } from 'react-router-dom'
import { ArrowRight, Bell, CalendarDays, FileText, Receipt, Shield, Sparkles, WalletCards } from 'lucide-react'
import Footer from '../components/Footer.jsx'
import LanguageToggle from '../components/LanguageToggle.jsx'
import Logo from '../components/Logo.jsx'
import { useLang } from '../contexts/LanguageContext.jsx'
import { textFor } from '../lib/uiText.js'

export default function Landing() {
  const { lang } = useLang()
  const ui = textFor(lang)
  return <div className="min-h-screen bg-white"><header className="absolute top-0 inset-x-0 z-20"><div className="container-app flex items-center justify-between h-16"><Logo /><div className="flex items-center gap-3"><Link to="/pricing" className="hidden sm:block text-sm font-semibold text-ink-700 hover:text-ink-900">{ui.landing.pricing}</Link><LanguageToggle /><Link to="/login" className="hidden sm:inline-flex btn-ghost text-sm">{ui.landing.login}</Link><Link to="/signup" className="btn-primary text-sm !px-4 !py-2">{ui.landing.start}</Link></div></div></header><section className="hero-gradient pt-32 pb-20 sm:pt-40 sm:pb-28"><div className="container-app"><div className="max-w-3xl mx-auto text-center animate-fade-up"><span className="badge bg-brand-50 text-brand-700 mb-5"><Sparkles className="w-3.5 h-3.5" /> {ui.landing.badge}</span><h1 className="font-display text-4xl sm:text-5xl md:text-6xl font-extrabold text-ink-900 leading-[1.05]">{ui.landing.headline}</h1><p className="mt-5 text-lg sm:text-xl text-ink-600 max-w-2xl mx-auto">{ui.landing.sub}</p><div className="mt-8 flex flex-col sm:flex-row justify-center gap-3"><Link to="/signup" className="btn-primary">{ui.landing.start} <ArrowRight className="w-4 h-4" /></Link><Link to="/pricing" className="btn-secondary">{ui.landing.viewPlans}</Link></div><p className="mt-3 text-xs text-ink-400">{ui.landing.disclaimer}</p></div><HeroMock ui={ui} /></div></section><section className="py-20"><div className="container-app"><div className="max-w-2xl mx-auto text-center"><h2 className="text-3xl font-extrabold text-ink-900">{ui.landing.core}</h2><p className="mt-3 text-ink-600">{ui.landing.coreSub}</p></div><div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-4 gap-5"><Feature icon={CalendarDays} title={ui.landing.today} text={ui.landing.todayText} /><Feature icon={Bell} title={ui.landing.reminders} text={ui.landing.remindersText} /><Feature icon={Receipt} title={ui.landing.expenses} text={ui.landing.expensesText} /><Feature icon={FileText} title={ui.landing.summary} text={ui.landing.summaryText} /></div></div></section><section className="py-16 bg-ink-50 border-y border-ink-100"><div className="container-app grid sm:grid-cols-3 gap-6"><Value icon={WalletCards} title={ui.landing.freeWorks} text={ui.landing.freeWorksText} /><Value icon={Sparkles} title={ui.landing.lightAI} text={ui.landing.lightAIText} /><Value icon={Shield} title={ui.landing.controlled} text={ui.landing.controlledText} /></div></section><Footer /></div>
}
function HeroMock({ ui }) { return <div className="mt-12 mx-auto max-w-md card p-4 text-left shadow-xl"><div className="flex items-center justify-between"><p className="font-bold text-ink-900">{ui.today.title}</p><span className="badge bg-brand-50 text-brand-700">{ui.smart.costControlled}</span></div><div className="mt-4 space-y-3"><MiniRow title={ui.today.quickTitle} text={ui.today.quickPlaceholder} /><MiniRow title={ui.expenses.title} text={`${ui.summary.business} + ${ui.summary.personal}`} /><MiniRow title={ui.summary.title} text={ui.summary.subtitle} /></div></div> }
function MiniRow({ title, text }) { return <div className="rounded-xl border border-ink-100 p-3"><p className="text-sm font-bold text-ink-900">{title}</p><p className="text-xs text-ink-500 mt-1">{text}</p></div> }
function Feature({ icon: Icon, title, text }) { return <div className="card p-5"><Icon className="w-6 h-6 text-brand-600" /><h3 className="mt-3 font-bold text-ink-900">{title}</h3><p className="mt-2 text-sm text-ink-500">{text}</p></div> }
function Value({ icon: Icon, title, text }) { return <div className="flex gap-3"><div className="w-11 h-11 rounded-2xl bg-white border border-ink-100 flex items-center justify-center"><Icon className="w-5 h-5 text-brand-600" /></div><div><h3 className="font-bold text-ink-900">{title}</h3><p className="text-sm text-ink-500 mt-1">{text}</p></div></div> }
