import { useMemo, useState } from 'react'
import { Bell, CheckCircle2, Plus, Trash2, RotateCcw } from 'lucide-react'
import Modal from '../components/Modal.jsx'
import { useLang } from '../contexts/LanguageContext.jsx'
import { useLocalStore } from '../lib/useLocalStore.js'
import { STORAGE_KEYS, CATEGORIES, todayISO, parseNaturalReminder } from '../lib/lifeStore.js'
import { categoryLabel, repeatLabel, textFor } from '../lib/uiText.js'

export default function Reminders() {
  const { lang } = useLang()
  const ui = textFor(lang)
  const [items, api] = useLocalStore(STORAGE_KEYS.reminders, [])
  const [open, setOpen] = useState(false)
  const active = useMemo(() => items.filter((x) => !x.done), [items])
  const done = useMemo(() => items.filter((x) => x.done).slice(0, 20), [items])
  return <div className="container-app py-6 sm:py-8"><Header onAdd={() => setOpen(true)} ui={ui} /><section className="mt-5 grid lg:grid-cols-2 gap-4"><ReminderCard title={ui.reminders.active} items={active} api={api} lang={lang} /><ReminderCard title={ui.reminders.done} items={done} api={api} done lang={lang} /></section><ReminderModal open={open} onClose={() => setOpen(false)} onSave={(item) => { api.add(item); setOpen(false) }} lang={lang} /></div>
}
function Header({ onAdd, ui }) { return <div className="flex items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-ink-900 flex items-center gap-2"><Bell className="w-7 h-7 text-brand-600" /> {ui.reminders.title}</h1><p className="text-ink-500 mt-1">{ui.reminders.subtitle}</p></div><button onClick={onAdd} className="btn-primary"><Plus className="w-4 h-4" /> {ui.common.new}</button></div> }
function ReminderCard({ title, items, api, done, lang }) { const ui = textFor(lang); return <div className="card p-5"><h2 className="font-bold text-ink-900">{title}</h2>{items.length === 0 ? <p className="py-10 text-center text-sm text-ink-400">{ui.common.noData}</p> : <ul className="mt-3 divide-y divide-ink-100">{items.map((r) => <li key={r.id} className="py-3 flex items-start justify-between gap-3"><div><p className="font-semibold text-ink-900">{r.title}</p><p className="text-xs text-ink-500">{r.date || ui.today.noDate} {r.time ? '• ' + r.time : ''} • {categoryLabel(r.category, lang)} {r.repeat !== 'none' ? '• ' + repeatLabel(r.repeat, lang) : ''}</p></div><div className="flex gap-2">{done ? <button onClick={() => api.update(r.id, { done: false, doneAt: null })} className="text-brand-600"><RotateCcw className="w-4 h-4" /></button> : <button onClick={() => api.update(r.id, { done: true, doneAt: new Date().toISOString() })} className="text-brand-600"><CheckCircle2 className="w-5 h-5" /></button>}<button onClick={() => api.remove(r.id)} className="text-ink-300 hover:text-rose-600"><Trash2 className="w-4 h-4" /></button></div></li>)}</ul>}</div> }
function ReminderModal({ open, onClose, onSave, lang }) { const ui = textFor(lang); const [quick, setQuick] = useState(''); const [form, setForm] = useState({ title: '', date: todayISO(), time: '', category: 'personal', repeat: 'none', notes: '' }); const applyQuick = () => setForm({ ...form, ...parseNaturalReminder(quick) }); const save = () => { const item = { ...form, done: false }; if (!item.title) return; onSave(item); setForm({ title: '', date: todayISO(), time: '', category: 'personal', repeat: 'none', notes: '' }); setQuick('') }; return <Modal open={open} onClose={onClose} title={ui.reminders.newTitle} footer={<><button className="btn-secondary" onClick={onClose}>{ui.common.cancel}</button><button className="btn-primary" onClick={save}>{ui.common.save}</button></>}><label className="label">{ui.reminders.naturalText}</label><div className="flex gap-2 mb-3"><input className="input" value={quick} onChange={(e) => setQuick(e.target.value)} placeholder={ui.reminders.naturalPlaceholder} /><button className="btn-secondary !px-3" onClick={applyQuick}>{ui.reminders.read}</button></div><Field label={ui.common.title} value={form.title} onChange={(v) => setForm({ ...form, title: v })} /><div className="grid grid-cols-2 gap-3"><Field label={ui.common.date} type="date" value={form.date} onChange={(v) => setForm({ ...form, date: v })} /><Field label={ui.common.time} type="time" value={form.time} onChange={(v) => setForm({ ...form, time: v })} /></div><label className="label">{ui.common.category}</label><select className="input mb-3" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{CATEGORIES.map((c) => <option key={c.key} value={c.key}>{categoryLabel(c.key, lang)}</option>)}</select><label className="label">Repeat</label><select className="input mb-3" value={form.repeat} onChange={(e) => setForm({ ...form, repeat: e.target.value })}><option value="none">{repeatLabel('none', lang)}</option><option value="daily">{repeatLabel('daily', lang)}</option><option value="weekly">{repeatLabel('weekly', lang)}</option><option value="monthly">{repeatLabel('monthly', lang)}</option></select><Field label={ui.reminders.notes} value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} /></Modal> }
function Field({ label, value, onChange, type = 'text' }) { return <label className="block mb-3"><span className="label">{label}</span><input className="input" type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label> }
