import { useMemo, useState } from 'react'
import { Bell, CheckCircle2, Plus, Trash2, RotateCcw } from 'lucide-react'
import Modal from '../components/Modal.jsx'
import { useLocalStore } from '../lib/useLocalStore.js'
import { STORAGE_KEYS, CATEGORIES, todayISO, parseNaturalReminder } from '../lib/lifeStore.js'

export default function Reminders() {
  const [items, api] = useLocalStore(STORAGE_KEYS.reminders, [])
  const [open, setOpen] = useState(false)
  const active = useMemo(() => items.filter((x) => !x.done), [items])
  const done = useMemo(() => items.filter((x) => x.done).slice(0, 20), [items])
  return <div className="container-app py-6 sm:py-8"><Header onAdd={() => setOpen(true)} /><section className="mt-5 grid lg:grid-cols-2 gap-4"><ReminderCard title="Active reminders" items={active} api={api} /><ReminderCard title="Done recently" items={done} api={api} done /></section><ReminderModal open={open} onClose={() => setOpen(false)} onSave={(item) => { api.add(item); setOpen(false) }} /></div>
}
function Header({ onAdd }) { return <div className="flex items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-ink-900 flex items-center gap-2"><Bell className="w-7 h-7 text-brand-600" /> Reminders</h1><p className="text-ink-500 mt-1">Việc một lần, việc lặp lại, family reminder, bill reminder — gom chung.</p></div><button onClick={onAdd} className="btn-primary"><Plus className="w-4 h-4" /> New</button></div> }
function ReminderCard({ title, items, api, done }) { return <div className="card p-5"><h2 className="font-bold text-ink-900">{title}</h2>{items.length === 0 ? <p className="py-10 text-center text-sm text-ink-400">Không có dữ liệu.</p> : <ul className="mt-3 divide-y divide-ink-100">{items.map((r) => <li key={r.id} className="py-3 flex items-start justify-between gap-3"><div><p className="font-semibold text-ink-900">{r.title}</p><p className="text-xs text-ink-500">{r.date || 'No date'} {r.time ? '• ' + r.time : ''} • {r.category} {r.repeat !== 'none' ? '• ' + r.repeat : ''}</p></div><div className="flex gap-2">{done ? <button onClick={() => api.update(r.id, { done: false, doneAt: null })} className="text-brand-600"><RotateCcw className="w-4 h-4" /></button> : <button onClick={() => api.update(r.id, { done: true, doneAt: new Date().toISOString() })} className="text-brand-600"><CheckCircle2 className="w-5 h-5" /></button>}<button onClick={() => api.remove(r.id)} className="text-ink-300 hover:text-rose-600"><Trash2 className="w-4 h-4" /></button></div></li>)}</ul>}</div> }
function ReminderModal({ open, onClose, onSave }) { const [quick, setQuick] = useState(''); const [form, setForm] = useState({ title: '', date: todayISO(), time: '', category: 'personal', repeat: 'none', notes: '' }); const applyQuick = () => setForm({ ...form, ...parseNaturalReminder(quick) }); const save = () => { const item = { ...form, done: false }; if (!item.title) return; onSave(item); setForm({ title: '', date: todayISO(), time: '', category: 'personal', repeat: 'none', notes: '' }); setQuick('') }; return <Modal open={open} onClose={onClose} title="New reminder" footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" onClick={save}>Save</button></>}><label className="label">Natural text</label><div className="flex gap-2 mb-3"><input className="input" value={quick} onChange={(e) => setQuick(e.target.value)} placeholder="nhắc tôi uống thuốc mỗi ngày 9pm" /><button className="btn-secondary !px-3" onClick={applyQuick}>Read</button></div><Field label="Title" value={form.title} onChange={(v) => setForm({ ...form, title: v })} /><div className="grid grid-cols-2 gap-3"><Field label="Date" type="date" value={form.date} onChange={(v) => setForm({ ...form, date: v })} /><Field label="Time" type="time" value={form.time} onChange={(v) => setForm({ ...form, time: v })} /></div><label className="label">Category</label><select className="input mb-3" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{CATEGORIES.map((c) => <option key={c.key} value={c.key}>{c.label} / {c.vi}</option>)}</select><label className="label">Repeat</label><select className="input mb-3" value={form.repeat} onChange={(e) => setForm({ ...form, repeat: e.target.value })}><option value="none">None</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><Field label="Notes" value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} /></Modal> }
function Field({ label, value, onChange, type = 'text' }) { return <label className="block mb-3"><span className="label">{label}</span><input className="input" type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label> }
