export const taxCopy = {
  vi: {
    title: 'Tổng kết cuối năm',
    sub: 'Gom dữ liệu để bạn đưa cho người làm thuế: tiền trả thợ, income, chi tiêu kinh doanh. App chỉ sắp xếp số liệu, không làm form thuế và không tư vấn thuế.',
    workers: 'Tiền trả thợ / nhân viên',
    addWorker: 'Thêm thợ',
    income: 'Income kinh doanh',
    addIncome: 'Thêm income',
    expenses: 'Chi tiêu kinh doanh',
    exportWorkers: 'CSV thợ',
    exportIncome: 'CSV income',
    exportExpenses: 'CSV chi tiêu',
    exportPdf: 'PDF cuối năm',
    exportPackage: 'CSV gộp',
    save: 'Lưu', close: 'Đóng', delete: 'Xóa', type: 'Loại',
    name: 'Tên thợ / nhân viên', ssn: 'SSN hoặc EIN', address: 'Địa chỉ',
    workPay: 'Tiền làm', tips: 'Tiền tip', total: 'Tổng cộng', year: 'Năm thuế', notes: 'Ghi chú',
    source: 'Nguồn income', category: 'Loại income', amount: 'Số tiền', date: 'Ngày',
    emptyWorkers: 'Chưa có dòng nào. Thêm thợ đầu tiên để cuối năm có sẵn.',
    emptyIncome: 'Chưa có income kinh doanh. Ghi dần để cuối năm khỏi nhớ.',
    emptyExpenses: 'Chưa có chi tiêu kinh doanh nào trong năm nay.',
    businessIncome: 'Income kinh doanh', workerTotal: 'Tiền trả thợ', businessExpenseTotal: 'Chi tiêu kinh doanh', netBusiness: 'Ước tính còn lại',
    warning: 'SSN/EIN là thông tin nhạy cảm. Chỉ nhập khi thật sự cần đưa cho người làm thuế. App này chỉ sắp xếp dữ liệu, không tư vấn thuế.',
    runSql: 'Nếu trang báo thiếu bảng/cột, chạy supabase/migration_004_tax_worker_income.sql trong Supabase trước.',
    incomeCategories: { salon_income: 'Income tiệm nail', booth_rent: 'Booth rent', uber: 'Uber', doordash: 'DoorDash', other_business: 'Kinh doanh khác' },
  },
  en: {
    title: 'Year-end summary',
    sub: 'Organizes data for your tax preparer: worker pay, business income, business expenses. The app organizes records — it does not prepare tax forms or give tax advice.',
    workers: 'Worker pay',
    addWorker: 'Add worker',
    income: 'Business income',
    addIncome: 'Add income',
    expenses: 'Business expenses',
    exportWorkers: 'Workers CSV',
    exportIncome: 'Income CSV',
    exportExpenses: 'Expenses CSV',
    exportPdf: 'Year PDF',
    exportPackage: 'Combined CSV',
    save: 'Save', close: 'Cancel', delete: 'Delete', type: 'Type', name: 'Worker / employee name', ssn: 'SSN or EIN', address: 'Address',
    workPay: 'Work pay', tips: 'Tips', total: 'Total', year: 'Tax year', notes: 'Notes', source: 'Income source', category: 'Income type', amount: 'Amount', date: 'Date',
    emptyWorkers: 'No worker records yet. Add the first one and the year fills in as you go.',
    emptyIncome: 'No business income yet. Log a little at a time and year-end will be easy.',
    emptyExpenses: 'No business expenses recorded this year.',
    businessIncome: 'Business income', workerTotal: 'Worker payments', businessExpenseTotal: 'Business expenses', netBusiness: 'Estimated net',
    warning: 'SSN/EIN is sensitive. Only enter it if your tax preparer needs it. The app organizes records; it does not provide tax advice.',
    runSql: 'If this page says tables/columns are missing, run supabase/migration_004_tax_worker_income.sql in Supabase first.',
    incomeCategories: { salon_income: 'Nail salon income', booth_rent: 'Booth rent', uber: 'Uber', doordash: 'DoorDash', other_business: 'Other business' },
  },
}
