export const taxCopy = {
  vi: {
    title: 'Hồ sơ thuế Business — 1099 / W-2',
    sub: 'Khu riêng cho chủ tiệm/business: điền 1099/W-2, doanh thu business, chi tiêu mỗi ngày/mỗi tháng và xuất file cho người làm thuế. Cá nhân vẫn nằm riêng ở Hóa đơn/Chi tiêu/Tổng kết.',
    workers: '1099 / W-2 — Thợ & nhân viên',
    addWorker: 'Thêm 1099 / W-2',
    income: 'Doanh thu business',
    addIncome: 'Thêm doanh thu business',
    expenses: 'Chi tiêu business',
    expenseSub: 'Ghi chi tiêu business hằng ngày/hằng tháng: vật tư, rent, điện nước, phone/internet, quảng cáo, sửa chữa, kế toán…',
    addExpense: 'Thêm chi tiêu business',
    exportWorkers: 'CSV 1099/W-2',
    exportIncome: 'CSV doanh thu',
    exportExpenses: 'CSV chi tiêu',
    exportPdf: 'PDF tóm tắt',
    exportPackage: 'Gói CSV cho tax preparer',
    save: 'Lưu', close: 'Đóng', delete: 'Xóa', type: 'Loại',
    name: 'Tên thợ / nhân viên', ssn: 'SSN hoặc EIN', address: 'Địa chỉ',
    workPay: 'Tiền làm', tips: 'Tiền tip', total: 'Tổng cộng', year: 'Năm thuế', notes: 'Ghi chú',
    source: 'Nguồn income', category: 'Phân loại', amount: 'Số tiền', date: 'Ngày', expenseName: 'Tên chi tiêu',
    emptyWorkers: 'Chưa có 1099/W-2. Thêm thợ/nhân viên đầu tiên để cuối năm khỏi lục giấy.',
    emptyIncome: 'Chưa có doanh thu business. Ghi dần để cuối năm khỏi nhớ.',
    emptyExpenses: 'Chưa có chi tiêu business nào trong năm nay. Bấm thêm để ghi hằng ngày hoặc hằng tháng.',
    businessIncome: 'Doanh thu business', workerTotal: 'Tiền trả thợ', businessExpenseTotal: 'Chi tiêu business', netBusiness: 'Ước tính còn lại',
    personalNotice: 'Bạn đang ở khu Cá nhân. Trang này là khu Business riêng. Có thể đổi sang Business bằng nút chuyển ở trên hoặc trong Cài đặt.',
    warning: 'SSN/EIN là thông tin nhạy cảm. Chỉ nhập khi thật sự cần đưa cho người làm thuế. App này giúp chuẩn bị hồ sơ 1099/W-2 và tổng kết business, nhưng không tư vấn thuế và không tự nộp IRS forms.',
    runSql: 'Trang business cần được kết nối đúng bảng dữ liệu. Nếu vẫn báo lỗi, kiểm tra lại phần Supabase setup cho Tax/Business.',
    incomeCategories: { salon_income: 'Income tiệm nail', service_sales: 'Service sales', product_sales: 'Product sales', booth_rent: 'Booth rent', uber: 'Uber', doordash: 'DoorDash', other_business: 'Kinh doanh khác' },
    expenseCategories: {
      supplies: 'Supplies / vật tư', utilities: 'Utilities / điện nước', rent: 'Rent / lease', payroll: 'Labor / payroll', insurance: 'Insurance', advertising: 'Advertising / marketing', phone_internet: 'Phone / Internet', repairs: 'Repairs / maintenance', office: 'Office expense', accounting: 'Accounting', legal_professional: 'Legal / professional fee', taxes: 'Taxes', car_truck: 'Car / truck', fuel: 'Fuel / oil', gift: 'Gift', other_business: 'Other business', salon: 'Salon', supply: 'Supply', business: 'Business'
    },
    prepCards: [
      { icon: 'workers', title: '1099 & W-2 rõ ràng', body: 'Dành cho chủ tiệm/chủ business: lưu tên, SSN/EIN, địa chỉ, tiền làm và tip. 1099 dùng cho contractor; W-2 dùng cho employee.', stat: (c) => `${c.contractors1099} 1099 • ${c.w2} W-2` },
      { icon: 'exports', title: 'Xuất file cho người làm thuế', body: 'Có CSV riêng cho 1099/W-2, income, expenses và một gói CSV gộp để gửi tax preparer.', stat: (c) => `${c.workers} workers • ${c.income} income • ${c.expenses} expenses` },
      { icon: 'forms', title: 'Theo form giấy tax', body: 'Doanh thu và chi tiêu business được gom theo kiểu form bạn gửi: doanh thu ở trên, chi tiêu ở dưới, cuối năm xuất tổng kết.', stat: null },
      { icon: 'safety', title: 'Cá nhân tách riêng', body: 'Hóa đơn/Chi tiêu cá nhân vẫn giữ hiện tại. Dữ liệu business nằm riêng trong Hồ sơ thuế Business; nhắc việc dùng chung cho cả hai.', stat: null },
    ],
  },
  en: {
    title: 'Hồ sơ thuế Business — 1099 / W-2',
    sub: 'A separate owner workspace for 1099/W-2, business income, daily/monthly business expenses, and tax-preparer exports. Personal bills/expenses stay separate.',
    workers: '1099 / W-2 workers',
    addWorker: 'Add 1099 / W-2',
    income: 'Doanh thu business',
    addIncome: 'Add business income',
    expenses: 'Chi tiêu business',
    expenseSub: 'Track business expenses daily/monthly: supplies, rent, utilities, phone/internet, advertising, repairs, accounting, and more.',
    addExpense: 'Add business expense',
    exportWorkers: '1099/W-2 CSV',
    exportIncome: 'Income CSV',
    exportExpenses: 'Expenses CSV',
    exportPdf: 'Summary PDF',
    exportPackage: 'Tax preparer CSV package',
    save: 'Save', close: 'Cancel', delete: 'Delete', type: 'Type', name: 'Worker / employee name', ssn: 'SSN or EIN', address: 'Address',
    workPay: 'Work pay', tips: 'Tips', total: 'Total', year: 'Tax year', notes: 'Notes', source: 'Income source', category: 'Category', amount: 'Amount', date: 'Date', expenseName: 'Expense title',
    emptyWorkers: 'No 1099/W-2 records yet. Add the first contractor or employee and year-end will build as you go.',
    emptyIncome: 'No business income yet. Log a little at a time and year-end will be easy.',
    emptyExpenses: 'No business expenses recorded this year. Add daily or monthly expenses here.',
    businessIncome: 'Business income', workerTotal: 'Worker payments', businessExpenseTotal: 'Business expenses', netBusiness: 'Estimated net',
    personalNotice: 'You are in Personal workspace. This is the separate Business area. Use the switch button at the top or Settings to move to Business.',
    warning: 'SSN/EIN is sensitive. Only enter it if your tax preparer needs it. The app helps organize 1099/W-2 and business records; it does not provide tax advice or file IRS forms.',
    runSql: 'The business area needs the correct database tables. If this still shows an error, check the Supabase setup for Tax/Business.',
    incomeCategories: { salon_income: 'Nail salon income', service_sales: 'Service sales', product_sales: 'Product sales', booth_rent: 'Booth rent', uber: 'Uber', doordash: 'DoorDash', other_business: 'Other business' },
    expenseCategories: {
      supplies: 'Supplies', utilities: 'Utilities', rent: 'Rent / lease', payroll: 'Labor / payroll', insurance: 'Insurance', advertising: 'Advertising / marketing', phone_internet: 'Phone / Internet', repairs: 'Repairs / maintenance', office: 'Office expense', accounting: 'Accounting', legal_professional: 'Legal / professional fees', taxes: 'Taxes', car_truck: 'Car / truck', fuel: 'Fuel / oil', gift: 'Gift', other_business: 'Other business', salon: 'Salon', supply: 'Supply', business: 'Business'
    },
    prepCards: [
      { icon: 'workers', title: 'Clear 1099 & W-2 records', body: 'For business owners: save name, SSN/EIN, address, work pay, and tips. Use 1099 for contractors and W-2 for employees.', stat: (c) => `${c.contractors1099} 1099 • ${c.w2} W-2` },
      { icon: 'exports', title: 'Files for your tax preparer', body: 'Export separate CSV files for 1099/W-2, income, expenses, plus one combined tax package.', stat: (c) => `${c.workers} workers • ${c.income} income • ${c.expenses} expenses` },
      { icon: 'forms', title: 'Based on paper tax sheets', body: 'Business income/expenses follow the style of your tax sheets: income on top, expenses below, summary at year-end.', stat: null },
      { icon: 'safety', title: 'Personal stays separate', body: 'Personal Bills/Expenses remain unchanged. Business data lives in the Business Tax Center; reminders work for both.', stat: null },
    ],
  },
}
